{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Библиотеки"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import neptune\n",
    "import pandas as pd\n",
    "\n",
    "from cv import get_indices\n",
    "from load_data import load\n",
    "from model_selection import training\n",
    "import random\n",
    "from NN import simple_torchpl\n",
    "from pl_framework import nn_training\n",
    "from pytorch_forecasting.metrics import MAPE\n",
    "import torch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: There is a new version of neptune-client 0.4.125 (installed: 0.4.124).\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Project(iliaavilov/SIBUR)"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "neptune.init('iliaavilov/SIBUR')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['NEPTUNE_API_TOKEN']=\"eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiYzI0ZTMzMDQtZTFmZi00ZjgxLWI4NGQtZGJiOWQyNDJiYjE5In0=\"\n",
    "os.environ['NEPTUNE_PROJECT']=\"iliaavilov/SIBUR\"\n",
    "os.environ['NEPTUNE_NOTEBOOK_ID']=\"3334104b-e4da-40ca-a353-d78790164c0b\"\n",
    "os.environ['NEPTUNE_NOTEBOOK_PATH']=\"Desktop/Projects/sibur_2020/modeling.ipynb\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Константы"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "data_path = 'data/'\n",
    "random_state = 54321"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Загрузка данных"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "train_features, train_targets, _ = load(data_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Валидация"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "cv = get_indices(train_targets, \n",
    "                 [(pd.to_datetime('2020-03-01 00:00:00'), pd.to_datetime('2020-03-15 00:00:00')),\n",
    "                  (pd.to_datetime('2020-03-15 00:00:00'), pd.to_datetime('2020-03-31 00:00:00')),\n",
    "                  (pd.to_datetime('2020-03-31 00:00:00'), pd.to_datetime('2020-04-15 00:00:00'))\n",
    "                 ],\n",
    "                 first_train = True\n",
    "                )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "#train_targets = train_targets.drop('timestamp', axis = 'columns')\n",
    "#train_features = train_features.drop('timestamp', axis = 'columns')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Подбор модели"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "heading_collapsed": true
   },
   "source": [
    "## NN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "hidden": true
   },
   "outputs": [],
   "source": [
    "%%capture\n",
    "for loss in ['MSE', 'MAE', 'MAPE']:\n",
    "    for target in ['B_C2H6', 'B_C3H8', 'B_iC4H10', 'B_nC4H10']:\n",
    "        my_training = training(name = target, nn_model = simple_torchpl, training_nn = nn_training,\n",
    "                               description = 'Ffill. New train for each fold. Simple nn.2 Linears. 2 drops. loss: {}\\\n",
    "                               Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates\\\n",
    "                               No normalisation. Only first 2 fold and test set(last fold).\\\n",
    "                               Dropped data before 2020-02-15 00:00:00'.format(loss),\n",
    "                               upload_source_files = ['cv.py', \n",
    "                                                      'load_data.py', \n",
    "                                                      'model_selection.py',\n",
    "                                                      'NN.py',\n",
    "                                                      'pl_framework.py',\n",
    "                                                      'preprocessing.py'])\n",
    "        my_training.set_up_studying(random_state = random_state)\n",
    "\n",
    "        model = 'torch'\n",
    "\n",
    "        def params_func(trial, X):\n",
    "            return(\n",
    "                {\n",
    "                    'target': target,\n",
    "                    'n_h_1': trial.suggest_int('n_h_1', 10, 1000),\n",
    "                    'batch_size': trial.suggest_int('batch_size', 10, 800),\n",
    "                    'p_1': trial.suggest_uniform('p_1', 0, 1),\n",
    "                    'p_2': trial.suggest_uniform('p_2', 0, 1),\n",
    "                    'lr': trial.suggest_loguniform('lr', 0.0001, 0.2),\n",
    "                    'weight_decay': trial.suggest_uniform('weight_decay', 0.0001, 1),\n",
    "                    'optimizer': 'AdamW',\n",
    "                    'loss': loss,\n",
    "                    'activation1': trial.suggest_categorical('activation1', ['Tanh','Hardtanh','Hardshrink', 'ELU' , \n",
    "                                                                             'SELU', 'ReLU', 'Tanhshrink', 'CELU']),\n",
    "                    'n_back_A_CH4': trial.suggest_int('n_back_A_CH4', 180, 220),\n",
    "                    'n_back_A_C2H6': trial.suggest_int('n_back_A_C2H6', 180, 220),\n",
    "                    'n_back_A_C3H8': trial.suggest_int('n_back_A_C3H8', 180, 220),\n",
    "                    'n_back_A_iC4H10': trial.suggest_int('n_back_A_iC4H10', 180, 220),\n",
    "                    'n_back_A_iC5H12': trial.suggest_int('n_back_A_iC5H12', 180, 220),\n",
    "                    'n_back_A_nC4H10': trial.suggest_int('n_back_A_nC4H10', 180, 220),\n",
    "                    'n_back_A_nC5H12': trial.suggest_int('n_back_A_nC5H12', 180, 220),\n",
    "                    'n_back_A_C6H14': trial.suggest_int('n_back_A_C6H14', 180, 220)\n",
    "\n",
    "        }\n",
    "            )\n",
    "\n",
    "\n",
    "        n_trials = 30\n",
    "        my_training.train(X = train_features, \n",
    "                          y = train_targets, \n",
    "                          cv = cv, \n",
    "                          model=model, \n",
    "                          params_func = params_func, \n",
    "                          n_trials = n_trials)\n",
    "        neptune.stop()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "heading_collapsed": true
   },
   "source": [
    "## LGBM"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "hidden": true,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "%%capture\n",
    "for boosting in ['gbdt']:\n",
    "    for objective in ['huber']:\n",
    "        for target in ['B_C3H8']:\n",
    "            my_training = training(name = target,\n",
    "                                   description = 'Ffill. 1 train for each fold. LGBM. boosting = {}, objective = {}\\\n",
    "                                   Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates. features+features 1, 2, 3 ... n days ago\\\n",
    "                                   No normalisation. Only first 2 fold and test set(last fold).feature fraction = 1\\\n",
    "                                   Dropped data before 2020-02-15 00:00:00'.format(boosting, objective),\n",
    "                                   upload_source_files = ['cv.py', \n",
    "                                                          'load_data.py', \n",
    "                                                          'model_selection.py',\n",
    "                                                          'NN.py',\n",
    "                                                          'pl_framework.py',\n",
    "                                                          'preprocessing.py'])\n",
    "            my_training.set_up_studying(random_state = random_state)\n",
    "\n",
    "            model = 'lgbm'\n",
    "\n",
    "            def params_func(trial, X):\n",
    "                return(\n",
    "                    {\n",
    "                        'target': target,\n",
    "                        'objective': objective,\n",
    "                        'boosting': boosting,\n",
    "                        'n_jobs': -1,\n",
    "                        'n_estimators': 1,\n",
    "                        'random_state': random_state,\n",
    "                        'bagging_fraction': 1,\n",
    "                        'feature_fraction': 1,\n",
    "                        'n_today': trial.suggest_int('n_today', 0, 100),\n",
    "                        'min_child_samples': trial.suggest_int('min_child_samples', 2, 256),\n",
    "                        'num_leaves': trial.suggest_int('num_leaves', 2, 256),\n",
    "                        'learning_rate': trial.suggest_uniform('learning_rate', 0.01, 1.5),\n",
    "                        'n_back_A_CH4': trial.suggest_int('n_back_A_CH4', 180, 220),\n",
    "                        'n_back_A_C2H6': trial.suggest_int('n_back_A_C2H6', 180, 220),\n",
    "                        'n_back_A_C3H8': trial.suggest_int('n_back_A_C3H8', 180, 220),\n",
    "                        'n_back_A_iC4H10': trial.suggest_int('n_back_A_iC4H10', 180, 220),\n",
    "                        'n_back_A_iC5H12': trial.suggest_int('n_back_A_iC5H12', 180, 220),\n",
    "                        'n_back_A_nC4H10': trial.suggest_int('n_back_A_nC4H10', 180, 220),\n",
    "                        'n_back_A_nC5H12': trial.suggest_int('n_back_A_nC5H12', 180, 220),\n",
    "                        'n_back_A_C6H14': trial.suggest_int('n_back_A_C6H14', 180, 220)\n",
    "\n",
    "\n",
    "            }\n",
    "                )\n",
    "\n",
    "\n",
    "            n_trials = 15000\n",
    "            my_training.train(X = train_features, \n",
    "                              y = train_targets, \n",
    "                              cv = cv, \n",
    "                              model = model, \n",
    "                              params_func = params_func, \n",
    "                              n_trials = n_trials)\n",
    "            neptune.stop()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "heading_collapsed": true
   },
   "source": [
    "## XGBOOST"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "hidden": true,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "%%capture\n",
    "for booster in ['gbtree']:\n",
    "    for objective in ['reg:tweedie', 'reg:gamma', 'reg:pseudohubererror', 'reg:logistic', 'reg:squaredlogerror', 'reg:squarederror']:\n",
    "        for target in ['B_C2H6', 'B_C3H8', 'B_iC4H10', 'B_nC4H10']:\n",
    "            my_training = training(name = target,\n",
    "                                   description = 'Ffill. 1 train for each fold. XGBOOST. boosting = {}, objective = {}\\\n",
    "                                   Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates\\\n",
    "                                   No normalisation. Only first 2 fold and test set(last fold).feature fraction = 1\\\n",
    "                                   Dropped data before 2020-02-15 00:00:00'.format(booster, objective),\n",
    "                                   upload_source_files = ['cv.py', \n",
    "                                                          'load_data.py', \n",
    "                                                          'model_selection.py',\n",
    "                                                          'NN.py',\n",
    "                                                          'pl_framework.py',\n",
    "                                                          'preprocessing.py'])\n",
    "            my_training.set_up_studying(random_state = random_state)\n",
    "\n",
    "            model = 'xgboost'\n",
    "\n",
    "            def params_func(trial, X):\n",
    "                return(\n",
    "                    {\n",
    "                        'target': target,\n",
    "                        'objective': objective,\n",
    "                        'booster': booster,\n",
    "                        'nthread': -1,\n",
    "                        'n_estimators': 3000,\n",
    "                        'random_state': random_state,\n",
    "                        'subsample': trial.suggest_uniform('subsample', 0.4, 1.0),\n",
    "                        'grow_policy': trial.suggest_categorical('grow_policy', ['depthwise', 'lossguide']),\n",
    "                        'max_leaves': trial.suggest_int('max_leaves', 2, 256),\n",
    "                        'learning_rate': trial.suggest_uniform('learning_rate', 0.01, 1.5),\n",
    "                        'n_back_A_CH4': trial.suggest_int('n_back_A_CH4', 180, 220),\n",
    "                        'n_back_A_C2H6': trial.suggest_int('n_back_A_C2H6', 180, 220),\n",
    "                        'n_back_A_C3H8': trial.suggest_int('n_back_A_C3H8', 180, 220),\n",
    "                        'n_back_A_iC4H10': trial.suggest_int('n_back_A_iC4H10', 180, 220),\n",
    "                        'n_back_A_iC5H12': trial.suggest_int('n_back_A_iC5H12', 180, 220),\n",
    "                        'n_back_A_nC4H10': trial.suggest_int('n_back_A_nC4H10', 180, 220),\n",
    "                        'n_back_A_nC5H12': trial.suggest_int('n_back_A_nC5H12', 180, 220),\n",
    "                        'n_back_A_C6H14': trial.suggest_int('n_back_A_C6H14', 180, 220)\n",
    "\n",
    "\n",
    "            }\n",
    "                )\n",
    "\n",
    "\n",
    "            n_trials = 3000\n",
    "            my_training.train(X = train_features, \n",
    "                              y = train_targets, \n",
    "                              cv = cv, \n",
    "                              model = model, \n",
    "                              params_func = params_func, \n",
    "                              n_trials = n_trials)\n",
    "            neptune.stop()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## SKLEARN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import SGDRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2020-12-12 20:03:45,075]\u001b[0m A new study created in memory with name: no-name-bf1b92ad-276d-4ae7-8f30-52f6a8203f2b\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,426]\u001b[0m Trial 0 finished with value: 0.06696306604099853 and parameters: {'n_back_A_C2H6': 210}. Best is trial 0 with value: 0.06696306604099853.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,779]\u001b[0m Trial 1 finished with value: 0.056542263282341854 and parameters: {'n_back_A_C2H6': 197}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,815]\u001b[0m Trial 2 finished with value: 0.06978198085353601 and parameters: {'n_back_A_C2H6': 182}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,851]\u001b[0m Trial 3 finished with value: 0.06696306604099853 and parameters: {'n_back_A_C2H6': 210}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,885]\u001b[0m Trial 4 finished with value: 0.08442863279894677 and parameters: {'n_back_A_C2H6': 219}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,921]\u001b[0m Trial 5 finished with value: 0.06148026113074674 and parameters: {'n_back_A_C2H6': 206}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,959]\u001b[0m Trial 6 finished with value: 0.05831138883897374 and parameters: {'n_back_A_C2H6': 192}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:45,995]\u001b[0m Trial 7 finished with value: 0.05831138883897374 and parameters: {'n_back_A_C2H6': 192}. Best is trial 1 with value: 0.056542263282341854.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:46,033]\u001b[0m Trial 8 finished with value: 0.053156772495044996 and parameters: {'n_back_A_C2H6': 202}. Best is trial 8 with value: 0.053156772495044996.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:46,070]\u001b[0m Trial 9 finished with value: 0.05119879315094207 and parameters: {'n_back_A_C2H6': 201}. Best is trial 9 with value: 0.05119879315094207.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:46,108]\u001b[0m Trial 10 finished with value: 0.08508771458493856 and parameters: {'n_back_A_C2H6': 220}. Best is trial 9 with value: 0.05119879315094207.\u001b[0m\n",
      "\u001b[32m[I 2020-12-12 20:03:46,145]\u001b[0m Trial 11 finished with value: 0.053156772495044996 and parameters: {'n_back_A_C2H6': 202}. Best is trial 9 with value: 0.05119879315094207.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-2ff48eaaf3b2>\", line 34, in <module>\n",
      "    my_training.train(X = train_features,\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in train\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\study.py\", line 306, in optimize\n",
      "    _optimize(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 55, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 156, in _optimize_sequential\n",
      "    trial = _run_trial(study, func, catch)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 189, in _run_trial\n",
      "    value = func(trial)\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in <lambda>\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 284, in objective\n",
      "    X_trans, y_trans, cv_trans, params_trans = preprocessing.preprocessing(X.copy(),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\preprocessing.py\", line 39, in preprocessing\n",
      "    fold[1][idx2] = fold[1][idx2] -  np.max(n_backs)\n",
      "  File \"<__array_function__ internals>\", line 5, in amax\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 2705, in amax\n",
      "    return _wrapreduction(a, np.maximum, 'max', axis, None, out,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 87, in _wrapreduction\n",
      "    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3145, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-ce8fe1e5aad4>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('capture', '', \"for target in ['C2H6', 'C3H8', 'iC4H10', 'nC4H10']:\\n    for random_state in [223, 245, 267, 12345, 998, 1456, 938, 223, 16]:\\n        my_training = training(name = 'B_' + target, sklearn_class = SGDRegressor,\\n                               description = 'Ffill. 1 train for each fold. Linear regression. WEIGHTED\\\\\\n                               Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates. Features = A_target, constant\\\\\\n                               No normalisation. Only first 2 fold and test set(last fold)\\\\\\n                               Dropped data before 2020-02-15 00:00:00',\\n                               upload_source_files = ['cv.py', \\n                                                      'load_data.py', \\n                                                      'model_selection.py',\\n                                                      'NN.py',\\n                                                      'pl_framework.py',\\n                                                      'preprocessing.py'])\\n        my_training.set_up_studying(random_state = random_state)\\n\\n        model = 'sklearn'\\n\\n        def params_func(trial, X):\\n            return(\\n                {\\n                    'target': target,\\n                    'random_state': random_state,\\n                    'loss': 'epsilon_insensitive',\\n                    'epsilon': 0,\\n                    'tol': 1e-5,\\n                    'n_back_A_{}'.format(target): trial.suggest_int('n_back_A_{}'.format(target), 180, 220)\\n\\n\\n        }\\n            )\\n\\n\\n        n_trials = 250\\n        my_training.train(X = train_features, \\n                          y = train_targets, \\n                          cv = cv, \\n                          model = model, \\n                          params_func = params_func, \\n                          n_trials = n_trials)\\n        neptune.stop()\\n\")\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2381, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-57>\", line 2, in capture\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magics\\execution.py\", line 1463, in capture\n",
      "    self.shell.run_cell(cell)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2876, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2927, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-2ff48eaaf3b2>\", line 34, in <module>\n",
      "    my_training.train(X = train_features,\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in train\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\study.py\", line 306, in optimize\n",
      "    _optimize(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 55, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 156, in _optimize_sequential\n",
      "    trial = _run_trial(study, func, catch)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 189, in _run_trial\n",
      "    value = func(trial)\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in <lambda>\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 284, in objective\n",
      "    X_trans, y_trans, cv_trans, params_trans = preprocessing.preprocessing(X.copy(),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\preprocessing.py\", line 39, in preprocessing\n",
      "    fold[1][idx2] = fold[1][idx2] -  np.max(n_backs)\n",
      "  File \"<__array_function__ internals>\", line 5, in amax\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 2705, in amax\n",
      "    return _wrapreduction(a, np.maximum, 'max', axis, None, out,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 87, in _wrapreduction\n",
      "    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3145, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-ce8fe1e5aad4>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('capture', '', \"for target in ['C2H6', 'C3H8', 'iC4H10', 'nC4H10']:\\n    for random_state in [223, 245, 267, 12345, 998, 1456, 938, 223, 16]:\\n        my_training = training(name = 'B_' + target, sklearn_class = SGDRegressor,\\n                               description = 'Ffill. 1 train for each fold. Linear regression. WEIGHTED\\\\\\n                               Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates. Features = A_target, constant\\\\\\n                               No normalisation. Only first 2 fold and test set(last fold)\\\\\\n                               Dropped data before 2020-02-15 00:00:00',\\n                               upload_source_files = ['cv.py', \\n                                                      'load_data.py', \\n                                                      'model_selection.py',\\n                                                      'NN.py',\\n                                                      'pl_framework.py',\\n                                                      'preprocessing.py'])\\n        my_training.set_up_studying(random_state = random_state)\\n\\n        model = 'sklearn'\\n\\n        def params_func(trial, X):\\n            return(\\n                {\\n                    'target': target,\\n                    'random_state': random_state,\\n                    'loss': 'epsilon_insensitive',\\n                    'epsilon': 0,\\n                    'tol': 1e-5,\\n                    'n_back_A_{}'.format(target): trial.suggest_int('n_back_A_{}'.format(target), 180, 220)\\n\\n\\n        }\\n            )\\n\\n\\n        n_trials = 250\\n        my_training.train(X = train_features, \\n                          y = train_targets, \\n                          cv = cv, \\n                          model = model, \\n                          params_func = params_func, \\n                          n_trials = n_trials)\\n        neptune.stop()\\n\")\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2381, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-57>\", line 2, in capture\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magics\\execution.py\", line 1463, in capture\n",
      "    self.shell.run_cell(cell)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2876, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2927, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-2ff48eaaf3b2>\", line 34, in <module>\n",
      "    my_training.train(X = train_features,\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in train\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\study.py\", line 306, in optimize\n",
      "    _optimize(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 55, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 156, in _optimize_sequential\n",
      "    trial = _run_trial(study, func, catch)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\optuna\\_optimize.py\", line 189, in _run_trial\n",
      "    value = func(trial)\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 55, in <lambda>\n",
      "    self.study.optimize(lambda trial: self.objective(trial, X, y, cv, model, params_func),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\model_selection.py\", line 284, in objective\n",
      "    X_trans, y_trans, cv_trans, params_trans = preprocessing.preprocessing(X.copy(),\n",
      "  File \"C:\\Users\\Sibmice\\Desktop\\Projects\\sibur_2020\\preprocessing.py\", line 39, in preprocessing\n",
      "    fold[1][idx2] = fold[1][idx2] -  np.max(n_backs)\n",
      "  File \"<__array_function__ internals>\", line 5, in amax\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 2705, in amax\n",
      "    return _wrapreduction(a, np.maximum, 'max', axis, None, out,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\numpy\\core\\fromnumeric.py\", line 87, in _wrapreduction\n",
      "    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3145, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-ce8fe1e5aad4>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('capture', '', \"for target in ['C2H6', 'C3H8', 'iC4H10', 'nC4H10']:\\n    for random_state in [223, 245, 267, 12345, 998, 1456, 938, 223, 16]:\\n        my_training = training(name = 'B_' + target, sklearn_class = SGDRegressor,\\n                               description = 'Ffill. 1 train for each fold. Linear regression. WEIGHTED\\\\\\n                               Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates. Features = A_target, constant\\\\\\n                               No normalisation. Only first 2 fold and test set(last fold)\\\\\\n                               Dropped data before 2020-02-15 00:00:00',\\n                               upload_source_files = ['cv.py', \\n                                                      'load_data.py', \\n                                                      'model_selection.py',\\n                                                      'NN.py',\\n                                                      'pl_framework.py',\\n                                                      'preprocessing.py'])\\n        my_training.set_up_studying(random_state = random_state)\\n\\n        model = 'sklearn'\\n\\n        def params_func(trial, X):\\n            return(\\n                {\\n                    'target': target,\\n                    'random_state': random_state,\\n                    'loss': 'epsilon_insensitive',\\n                    'epsilon': 0,\\n                    'tol': 1e-5,\\n                    'n_back_A_{}'.format(target): trial.suggest_int('n_back_A_{}'.format(target), 180, 220)\\n\\n\\n        }\\n            )\\n\\n\\n        n_trials = 250\\n        my_training.train(X = train_features, \\n                          y = train_targets, \\n                          cv = cv, \\n                          model = model, \\n                          params_func = params_func, \\n                          n_trials = n_trials)\\n        neptune.stop()\\n\")\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2381, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-57>\", line 2, in capture\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\magics\\execution.py\", line 1463, in capture\n",
      "    self.shell.run_cell(cell)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2876, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2927, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3145, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\Sibmice\\anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "%%capture\n",
    "for target in ['C2H6', 'C3H8', 'iC4H10', 'nC4H10']:\n",
    "    for random_state in [223, 245, 267, 12345, 998, 1456, 938, 223, 16]:\n",
    "        my_training = training(name = 'B_' + target, sklearn_class = SGDRegressor,\n",
    "                               description = 'Ffill. 1 train for each fold. Linear regression. WEIGHTED\\\n",
    "                               Separate shift for each feature. seq_len = 1.180-220 range for shift. No shift in rates. Features = A_target, constant\\\n",
    "                               No normalisation. Only first 2 fold and test set(last fold)\\\n",
    "                               Dropped data before 2020-02-15 00:00:00',\n",
    "                               upload_source_files = ['cv.py', \n",
    "                                                      'load_data.py', \n",
    "                                                      'model_selection.py',\n",
    "                                                      'NN.py',\n",
    "                                                      'pl_framework.py',\n",
    "                                                      'preprocessing.py'])\n",
    "        my_training.set_up_studying(random_state = random_state)\n",
    "\n",
    "        model = 'sklearn'\n",
    "\n",
    "        def params_func(trial, X):\n",
    "            return(\n",
    "                {\n",
    "                    'target': target,\n",
    "                    'random_state': random_state,\n",
    "                    'loss': 'epsilon_insensitive',\n",
    "                    'epsilon': 0,\n",
    "                    'tol': 1e-5,\n",
    "                    'n_back_A_{}'.format(target): trial.suggest_int('n_back_A_{}'.format(target), 180, 220)\n",
    "\n",
    "\n",
    "        }\n",
    "            )\n",
    "\n",
    "\n",
    "        n_trials = 250\n",
    "        my_training.train(X = train_features, \n",
    "                          y = train_targets, \n",
    "                          cv = cv, \n",
    "                          model = model, \n",
    "                          params_func = params_func, \n",
    "                          n_trials = n_trials)\n",
    "        neptune.stop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  },
  "latex_envs": {
   "LaTeX_envs_menu_present": true,
   "autoclose": false,
   "autocomplete": true,
   "bibliofile": "biblio.bib",
   "cite_by": "apalike",
   "current_citInitial": 1,
   "eqLabelWithNumbers": true,
   "eqNumInitial": 1,
   "hotkeys": {
    "equation": "Ctrl-E",
    "itemize": "Ctrl-I"
   },
   "labels_anchors": false,
   "latex_user_defs": false,
   "report_style_numbering": false,
   "user_envs_cfg": false
  },
  "neptune": {
   "notebookId": "3334104b-e4da-40ca-a353-d78790164c0b"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
